[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
itertools = "0.10.1"
pico-args = { version = "0.4.2", default-features = false, features = ["combined-flags"] }